-- Users Table

CREATE TABLE IF NOT EXISTS users (

id INTEGER PRIMARY KEY AUTOINCREMENT,

username TEXT NOT NULL,

email TEXT UNIQUE NOT NULL,

password TEXT NOT NULL,

wallet INTEGER DEFAULT 0,

created_at DATETIME DEFAULT CURRENT_TIMESTAMP

);-- Orders Table

CREATE TABLE IF NOT EXISTS orders (

id INTEGER PRIMARY KEY AUTOINCREMENT,

user_id INTEGER,

service TEXT,

quantity INTEGER,

amount INTEGER,

status TEXT DEFAULT 'Pending',

created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

FOREIGN KEY(user_id) REFERENCES users(id)

);-- Referral Table

CREATE TABLE IF NOT EXISTS referrals (

id INTEGER PRIMARY KEY AUTOINCREMENT,

user_id INTEGER,

referral_code TEXT UNIQUE,

referred_by TEXT,

created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

FOREIGN KEY(user_id) REFERENCES users(id)

);-- Withdrawals Table

CREATE TABLE IF NOT EXISTS withdrawals (

id INTEGER PRIMARY KEY AUTOINCREMENT,

user_id INTEGER,

amount INTEGER,

status TEXT DEFAULT 'Pending',

created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

FOREIGN KEY(user_id) REFERENCES users(id)

);-- Daily Tasks Table

CREATE TABLE IF NOT EXISTS tasks (

id INTEGER PRIMARY KEY AUTOINCREMENT,

title TEXT NOT NULL,

reward INTEGER DEFAULT 0,

created_at DATETIME DEFAULT CURRENT_TIMESTAMP

);



-- User Tasks Table

CREATE TABLE IF NOT EXISTS user_tasks (

id INTEGER PRIMARY KEY AUTOINCREMENT,

user_id INTEGER,

task_id INTEGER,

completed INTEGER DEFAULT 0,

created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

FOREIGN KEY(user_id) REFERENCES users(id),

FOREIGN KEY(task_id) REFERENCES tasks(id)

);